name: Nightly Build with Conventional Commits

on:
  push:
    branches:
      - main
  pull_request_target:
    types:
      - opened
      - synchronize
      - reopened

permissions:
  pull-requests: write
  contents: read

jobs:
  confirm-convention:
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@v4

      - name: confirm-convention
        id: check-commit
        continue-on-error: true
        uses: webiny/action-conventional-commits@v1.3.0

      - name: close-on-fail
        if: steps.check-commit.outcome == 'failure'
        uses: superbrothers/close-pull-request@v3
        with:
          comment: "PR closed due to not following commit convention"

  build_and_test:
    runs-on: ubuntu-24.04
    needs: confirm-convention

    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker
        uses: docker/setup-buildx-action@v3

      - name: Run docker-compose up
        run: |
          docker-compose -f docker-compose.yml up -d
          docker-compose build

      - name: Run Tests inside the web container
        run: docker-compose exec -T web pytest tests/

      - name: Shut down Docker Compose
        run: docker-compose down
