name: Nightly Build with Conventional Commits

on:
  push:
    branches:
      - main
  pull_request_target:
    types:
      - opened
      - synchronize
      - reopened
  schedule:
    - cron: '0 0 * * *'

permissions:
  pull-requests: write
  contents: read

jobs:
  confirm_commit_convention:
    runs-on: ubuntu-24.04
    
    steps:
      - uses: actions/checkout@v4

      - name: confirm-convention
        id: check-commit
        continue-on-error: true
        uses: webiny/action-conventional-commits@v1.3.0

      - name: close-on-fail
        if: steps.check-commit.outcome == 'failure'
        uses: superbrothers/close-pull-request@v3
        with:
          comment: "PR closed due to not following commit convention"

      - name: Send Email on Commit Convention Failure
        if: failure()
        uses: dawidd6/action-send-mail@v4
        with:
          connection_url: ${{ secrets.MAIL_CONNECTION }}
          subject: "GitHub Actions: Commit Convention Check Failed"
          to: ${{ secrets.EMAIL_TO }}
          from: "Eleonore Cummings via Ethereal Email <${{ secrets.MAIL_USERNAME }}>"
          body: "The commit message did not follow the conventional commit format. Please fix it before merging."

  build_and_test:
    runs-on: ubuntu-24.04
    if: ${{ github.event_name != 'pull_request_target' }}
    needs: confirm_commit_convention

    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker
        uses: docker/setup-buildx-action@v3

      - name: Set up Docker Compose
        uses: KengoTODA/actions-setup-docker-compose@v1
        with:
          version: '2.14.2'

      - name: Copy Environment Variables
        run: cp .env.example .env

      - name: Run Compose Up
        run: docker compose up -d

      - name: Run Alembic Migrations
        run: docker compose exec web alembic upgrade head

      - name: Run Tests
        run: docker compose exec web pytest

      - name: Send Email on Test Failure
        if: failure()
        uses: dawidd6/action-send-mail@v4
        with:
          connection_url: ${{ secrets.MAIL_CONNECTION }}
          subject: "GitHub Actions: Tests Failed"
          to: ${{ secrets.EMAIL_TO }}
          from: "Eleonore Cummings via Ethereal Email <${{ secrets.MAIL_USERNAME }}>"
          body: "Some tests failed in the latest build. Check GitHub Actions."

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
      
      - name: Build and Push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: drshooby/fastapi-beyond-crud:nightly
