name: Nightly Build with Conventional Commits

on:
  push:
    branches:
      - main
  pull_request_target:
    types:
      - opened
      - synchronize
      - reopened

permissions:
  pull-requests: write
  contents: read

jobs:
  confirm-convention:
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@v4

      - name: confirm-convention
        id: check-commit
        continue-on-error: true
        uses: webiny/action-conventional-commits@v1.3.0

      - name: close-on-fail
        if: steps.check-commit.outcome == 'failure'
        uses: superbrothers/close-pull-request@v3
        with:
          comment: "PR closed due to not following commit convention"

  build_and_test:
    runs-on: ubuntu-24.04
    needs: confirm-convention

    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker
        uses: docker/setup-buildx-action@v3

      - name: Set up Docker Compose
        uses: KengoTODA/actions-setup-docker-compose@v1
        with:
          version: '2.14.2'

      - name: Run Compoose Up
        run: docker compose up -d

      - name: Copy Environment Variables
        run: cp .env.example .env

      - name: Verify env
        run: cat .env

      - name: Check Services
        run: |
          docker compose ps
          docker compose logs -f web

      - name: Install Pytest
        run: pip install -U pytest
        
      - name: Run Tests
        run: docker compose exec web pytest
