name: Nightly Build with Conventional Commits

on:
  pull_request_target:
    types:
      - opened
      - synchronize
      - reopened
  schedule:
    - cron: "* * * * *"

permissions:
  pull-requests: write
  contents: read
      
jobs:
  confirm-convention-and-build:
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@v4

      - name: confirm-convention
        id: check-commit
        continue-on-error: true
        uses: webiny/action-conventional-commits@v1.3.0

      - name: close-on-fail
        if: steps.check-commit.outcome == 'failure'
        uses: superbrothers/close-pull-request@v3
        with:
          comment: "PR closed due to not following commit convention"
        
  build_and_push:
    runs-on: ubuntu-24.04
    needs: confirm-convention-and-build

    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker
        uses: docker/setup-buildx-action@v3

      - name: Build Docker Image
        run: docker build -t nightly

      - name: Run Tests
        run: docker run --rm nightly pytest tests/
        
      


      

    
